import TopBar from "@/app/components/topBar";
import "./globals.css";
import { Lato, Inter, Montserrat } from "next/font/google";
import NavBar from "@/app/components/navBar";
import Footer from "./components/footer";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Rectome Pharma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${inter.variable} ${montserrat.variable}`}
      >
        <TopBar />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
